In [ ]:
testfolder = "" # <- specify a filepath for testing PRESUME
PRESUME = "/Users/iwatano/Desktop/Dev/yachielab/PRESUME/PRESUME.py" # <- specify a filepath of PRESUME.py 

In [12]:
!python3 $PRESUME -h

usage: PRESUME.py [-h] [--param PARAM] [-V] [--monitor MONITOR] [-n N]
                  [--tree TREE] [-L L] [-f F] [--polyC] [-d D] [-s S] [-T T]
                  [-e E] [--gtrgamma GTRGAMMA] [-u U] [--ud UD] [--ld LD]
                  [-m M] [--constant CONSTANT] [--output OUTPUT] [--qsub]
                  [--idANC IDANC] [--tMorigin TMORIGIN] [--debug] [--bar]
                  [--viewANC] [--save] [--CV] [-r R] [--seed SEED]
                  [--inprob INPROB] [--inlength INLENGTH] [--delprob DELPROB]
                  [--dellength DELLENGTH] [--indels INDELS] [--chunks CHUNKS]
                  [--dop DOP] [--dist DIST] [--editprofile EDITPROFILE]

PRESUME.py

optional arguments:
  -h, --help            show this help message and exit
  --param PARAM         load argument file(csv file)
  -V, --version
  --monitor MONITOR     time limit (default=None)
  -n N                  required number of sequences: if you specified this
                        parameter, timelimit will b

In [17]:
out = "{}/test_1".format(testfolder)
!python3 $PRESUME --seed 0 -L 1000 -n 1000 --constant 0.1 --output $out


######     ######     #######     #####     #     #    #     #    #######
#     #    #     #    #          #     #    #     #    ##   ##    #
#     #    #     #    #          #          #     #    # # # #    #
######     ######     #####       #####     #     #    #  #  #    #####
#          #   #      #                #    #     #    #     #    #
#          #    #     #          #     #    #     #    #     #    #
#          #     #    #######     #####      #####     #     #    #######
Version:     1.0.0
Last update: April 24, 2020
GitHub:      https://github.com/yachielab/PRESUME

Generating a FASTA file...
Generating a Newick file......

Simulation end time point:         11.0
Number of generated sequences:     1024
Seed for random number generation: 0



In [18]:
out = "{}/test_2".format(testfolder)
!python3 $PRESUME --seed 0 -L 1000 -n 1000 -e 0.01 --gtrgamma default --output $out

Substitution rate matrix:
[[-0.0249975  0.0083325  0.0083325  0.0083325]
 [ 0.0083325 -0.0249975  0.0083325  0.0083325]
 [ 0.0083325  0.0083325 -0.0249975  0.0083325]
 [ 0.0083325  0.0083325  0.0083325 -0.0249975]]

######     ######     #######     #####     #     #    #     #    #######
#     #    #     #    #          #     #    #     #    ##   ##    #
#     #    #     #    #          #          #     #    # # # #    #
######     ######     #####       #####     #     #    #  #  #    #####
#          #   #      #                #    #     #    #     #    #
#          #    #     #          #     #    #     #    #     #    #
#          #     #    #######     #####      #####     #     #    #######
Version:     1.0.0
Last update: April 24, 2020
GitHub:      https://github.com/yachielab/PRESUME

Generating a FASTA file...
Generating a Newick file......

Simulation end time point:         12.0
Number of generated sequences:     1910
Seed for random number generation: 0



In [19]:
out = "{}/test_3".format(testfolder)
!python3 $PRESUME --seed 0 -L 1000 -n 1000 -s 0.1 --CV --gtrgamma default --output $out

Substitution rate matrix:
[[-0.0249975  0.0083325  0.0083325  0.0083325]
 [ 0.0083325 -0.0249975  0.0083325  0.0083325]
 [ 0.0083325  0.0083325 -0.0249975  0.0083325]
 [ 0.0083325  0.0083325  0.0083325 -0.0249975]]

######     ######     #######     #####     #     #    #     #    #######
#     #    #     #    #          #     #    #     #    ##   ##    #
#     #    #     #    #          #          #     #    # # # #    #
######     ######     #####       #####     #     #    #  #  #    #####
#          #   #      #                #    #     #    #     #    #
#          #    #     #          #     #    #     #    #     #    #
#          #     #    #######     #####      #####     #     #    #######
Version:     1.0.0
Last update: April 24, 2020
GitHub:      https://github.com/yachielab/PRESUME

Generating a FASTA file...
Generating a Newick file......

Simulation end time point:         11.060170321065144
Number of generated sequences:     1024
Seed for random number generation: 0



In [3]:
out = "{}/test_4".format(testfolder)
inprob = "/Users/iwatano/Desktop/tmp_PRESUME/20201122_debug/test_4/prob.txt"
length = "/Users/iwatano/Desktop/tmp_PRESUME/20201122_debug/test_4/length.txt"
!python3 $PRESUME -n 100 --seed 0 --output $out --inprob $inprob --inlength $length  --delprob $inprob --dellength $length --gtrgamma default


Substitution rate matrix:
[[-0.0249975  0.0083325  0.0083325  0.0083325]
 [ 0.0083325 -0.0249975  0.0083325  0.0083325]
 [ 0.0083325  0.0083325 -0.0249975  0.0083325]
 [ 0.0083325  0.0083325  0.0083325 -0.0249975]]

######     ######     #######     #####     #     #    #     #    #######
#     #    #     #    #          #     #    #     #    ##   ##    #
#     #    #     #    #          #          #     #    # # # #    #
######     ######     #####       #####     #     #    #  #  #    #####
#          #   #      #                #    #     #    #     #    #
#          #    #     #          #     #    #     #    #     #    #
#          #     #    #######     #####      #####     #     #    #######
Version:     1.0.0
Last update: April 24, 2020
GitHub:      https://github.com/yachielab/PRESUME

Generating a FASTA file...
Generating a Newick file......

Simulation end time point:         8.0
Number of generated sequences:     128
Seed for random number generation: 0



In [1]:
out = "{}/test_5".format(testfolder)
test_input = "/Users/iwatano/Desktop/tmp_PRESUME/20201122_debug/test_5/test_input.csv"
!python3 $PRESUME -n 100 --seed 0 --output $out --editprofile $test_input


######     ######     #######     #####     #     #    #     #    #######
#     #    #     #    #          #     #    #     #    ##   ##    #
#     #    #     #    #          #          #     #    # # # #    #
######     ######     #####       #####     #     #    #  #  #    #####
#          #   #      #                #    #     #    #     #    #
#          #    #     #          #     #    #     #    #     #    #
#          #     #    #######     #####      #####     #     #    #######
Version:     1.0.0
Last update: April 24, 2020
GitHub:      https://github.com/yachielab/PRESUME

Generating a FASTA file...
Generating a Newick file......

Simulation end time point:         8.0
Number of generated sequences:     128
Seed for random number generation: 0

